#!/bin/bash
# Summary: Shows the path to the file who set the php version

set -e
[ -n "$PHPDOCK_DEBUG" ] && set -x

# Set config variables
COMMAND=`basename $0 | cut -d- -f2`

# Provide phpdock completions
if [ "$1" = "--complete" ]; then
  if [ "$#" -eq 1 ]; then
    echo --apache
    echo --help
  fi
  exit 0
fi

function upsearch {
  slashes=${PWD//[^\/]/}
  directory="$PWD"
  for (( n=${#slashes}; n>0; --n ))
  do
    test -e "$directory/$1" && echo "$directory/$1" && return
    directory="$directory/.."
  done
}

# Config getopt
TEMP=`getopt -o '' --long apache -n $PROG -- "$@"`
eval set -- "$TEMP"

MODE=php
# Parse arguments
while true ; do
  case "$1" in
    --apache)
      MODE=apache
      PARAM=--apache
      shift;;
    --) shift ; break ;;
    *) echo "Internal error!" ; exit 1 ;;
  esac
done

if phpdock local $PARAM > /dev/null; then
  PHPVERSION=`upsearch ".$MODE-local-version"`
  echo `realpath $PHPVERSION`
elif phpdock global $PARAM > /dev/null; then
  echo $MAIN_PATH/etc/$MODE-version
else
  echo "No php version setted ($MODE)"
  exit 1
fi
