#!/bin/bash
# Summary: Show the current php version and its origin
# Usage: phpdock version
#
# Shows the currently selected php version and how it was
# selected. 
# To obtain only the version string, use `phpdock version-name'.
# To obtaing only the path to origin file who set the version, use
# `phpdock version-origin'.
#
# More information at https://github.com/lucasdc6/phpdock#readme

set -e
[ -n "$PHPDOCK_DEBUG" ] && set -x

# Set config variables
COMMAND=`basename $0 | cut -d- -f2`

# Provide phpdock completions
if [ "$1" = "--complete" ]; then
  if [ "$#" -eq 1 ]; then
    echo --help
  fi
  exit 0
fi

function upsearch {
  slashes=${PWD//[^\/]/}
  directory="$PWD"
  for (( n=${#slashes}; n>0; --n ))
  do
    test -e "$directory/$1" && echo "$directory/$1" && return
    directory="$directory/.."
  done
}

# Config getopt
TEMP=`getopt -o '' --long apache,name -n $PROG -- "$@"`
eval set -- "$TEMP"

# Parse arguments
while true ; do
  case "$1" in
    --apache)
      APACHE="--apache"
      shift;;
    --) shift ; break ;;
    *) echo "Internal error!" ; exit 1 ;;
  esac
done

if phpdock local > /dev/null; then
  ENVRC=`upsearch ".envrc"`
  echo "`phpdock-local $APACHE` (set by `realpath $ENVRC`)"
else
  echo "`phpdock-global $APACHE` (set by $MAIN_PATH/etc/php_global)"
fi
