#!/usr/bin/env bash
# Summary: Display prefix for a php docker version
# Usage: phpdock prefix [<version>]
#
# Displays complete image name of a php version. If no
# version is given, `phpdock prefix' displays the location of the
# currently selected version.

set -e
[ -n "$PHPDOCK_DEBUG" ] && set -x

# Provide phpdock completions
if [ "$1" = "--complete" ]; then
  if [ "$#" -eq 1 ]; then
    echo system
    echo --help
  fi
  exit 0
fi

if [ -n "$1" ]; then
  PHP_CLI_DOCKER_IMAGE="$1"
elif [ -z "$PHP_CLI_DOCKER_IMAGE" ]; then
  PHP_CLI_DOCKER_IMAGE="$(phpdock-version-name)"
fi

if [ "$PHP_CLI_DOCKER_IMAGE" = "system" ]; then
  whereis -b php | awk '{print $2}'
  exit 0
fi

containsElement () {
  local e match="$1"
  shift
  for e; do [[ "$e" == "$match" ]] && return 0; done
  return 1
}


PHPDOCK_PREFIX=(`docker images --format "{{.Repository}}:{{.Tag}}" $PHP_CLI_DOCKER_IMAGE`)

if ! containsElement $PHP_CLI_DOCKER_IMAGE ${PHPDOCK_PREFIX[@]} ; then
  echo "phpdock: version \`${PHP_CLI_DOCKER_IMAGE}' not installed" >&2
  exit 1
fi

echo $PHPDOCK_PREFIX
