#!/usr/bin/env bash
# Summary: List all available phpdock commands
# Usage: phpdock commands [--sh|--no-sh]

set -e

[ -n "$PHPDOCK_DEBUG" ] && set -x

COMMANDS=(`find $MAIN_PATH/libexec/phpdock-* -maxdepth 1 -type f -executable | rev | cut -d/ -f 1 | rev | uniq | sort`)

for COMMAND in ${COMMANDS[@]}; do
  echo ${COMMAND:8}
done
