#!/bin/bash
# Summary: Set or show the global php version
# Usage: phpdock global [-a|--apache]
#        phpdock global <version> [-a|--apache]
#        phpdock global --unset [-a|--apache]
#
# Set or show php global version setted
# By default, show php cli version
#
# You can override the global version at any time by setting a
# directory-specific version with 'phpdock local'.
#
# <version> should be a string matching a php version known to phpdock
# see 'phpdock versions'
#
# More information at https://github.com/lucasdc6/phpdock#readme

set -e
[ -n "$PHPDOCK_DEBUG" ] && set -x

# Set config variables
COMMAND=`basename $0 | cut -d- -f2`

# Provide phpdock completions
if [ "$1" = "--complete" ]; then
  if echo $@ | grep "\-\-apache" > /dev/null; then
    [ -f $MAIN_PATH/etc/versions/apache ] && cat $MAIN_PATH/etc/versions/apache
    echo --unset
  elif echo $@ | grep -v "\-\-help" > /dev/null; then
    echo system
    echo --apache
    echo --unset
    [ -f $MAIN_PATH/etc/versions/php ] && cat $MAIN_PATH/etc/versions/php
  fi
  if [ "$#" -eq 1 ]; then
    echo --help
  fi
  exit 0
fi

# Function to change global version of php
# Arguments
#   1: version to set as global
function change_global {
  if [ "$2" ]
  then
    phpdock-prefix $2 > /dev/null
    echo $2 > "$MAIN_PATH/etc/${1}-version"
    echo "Global php version setted to $2 in file $MAIN_PATH/etc/${1}-version"
  elif [ -f "$MAIN_PATH/etc/${1}-version" ]
  then
    cat $MAIN_PATH/etc/${1}-version
  else
    echo "$PROG: no php global version configured ($1 mode)"
    exit 1
  fi
}

# Config getopt
TEMP=`getopt -o a,u --long apache,unset -n $PROG -- "$@"`
eval set -- "$TEMP"

# default value of apache
MODE=php

# Parse arguments
while true ; do
  case "$1" in
    -a|--apache)
      MODE=apache
      shift;;
    --unset)
      ACTION=unset
      shift;;
    --) shift ; break ;;
    *) echo "Internal error!" ; exit 1 ;;
  esac
done

if [ "$ACTION" = "unset" ]; then
  rm $MAIN_PATH/etc/$MODE-version
  exit 0
fi

change_global $MODE $1
