#!/bin/bash
# Summary: List all php versions available to phpdock
# Usage: phpdock versions [--apache]
#
# List all php versions available to phpdock
# By default, show cli versions
#
# More information at https://github.com/lucasdc6/phpdock#readme

set -e
[ -n "$PHPDOCK_DEBUG" ] && set -x

# Set config variables
COMMAND=`basename $0 | cut -d- -f2`

PHP_IMAGES=( $(cat $MAIN_PATH/etc/repositories) )

# Function to get installed versions
# Arguments
#   1: type (cli|apache)
function show_versions {
  for IMAGE in "${PHP_IMAGES[@]}"
  do
    docker images | awk -v image=$IMAGE -v tag=$1 '($1 == image) && ($2 ~ tag) {print $1":"$2;}'
  done
}

# Config getopt
TEMP=`getopt -o '' --long apache -n $PROG -- "$@"`
eval set -- "$TEMP"

# default mode value
MODE="cli"

# Parse arguments
while true ; do
  case "$1" in
    --apache)
      MODE="apache"
      shift;;
    --) shift ; break ;;
    *) echo "Internal error!" ; exit 1 ;;
  esac
done

show_versions $MODE
