#!/bin/bash
# Summary: Shows the currently selected php version

set -e
[ -n "$PHPDOCK_DEBUG" ] && set -x

# Set config variables
COMMAND=`basename $0 | cut -d- -f2`

function upsearch {
  slashes=${PWD//[^\/]/}
  directory="$PWD"
  for (( n=${#slashes}; n>0; --n ))
  do
    test -e "$directory/$1" && echo "$directory/$1" && return
    directory="$directory/.."
  done
}

# Config getopt
TEMP=`getopt -o '' --long apache,name -n $PROG -- "$@"`
eval set -- "$TEMP"

# Parse arguments
while true ; do
  case "$1" in
    --apache)
      APACHE="--apache"
      shift;;
    --) shift ; break ;;
    *) echo "Internal error!" ; exit 1 ;;
  esac
done

if phpdock local > /dev/null; then
  ENVRC=`upsearch ".envrc"`
  echo `phpdock local $APACHE`
else
  echo `phpdock global $APACHE`
fi
