#!/usr/bin/env bash
# Usage: phpdock version-file-write <file> <version>

set -e
[ -n "$PHPDOCK_DEBUG" ] && set -x

# Provide phpdock completions
if [ "$1" = "--complete" ]; then
  if [ "$#" -eq 1 ]; then
    echo --help
  fi
  exit 0
fi

PHPDOCK_VERSION_FILE="$1"
PHPDOCK_VERSION="$2"

if [ -z "$PHPDOCK_VERSION" ] || [ -z "$PHPDOCK_VERSION_FILE" ]; then
  phpdock-help --usage version-file-write >&2
  exit 1
fi

# Make sure the specified version is installed.
phpdock-prefix "$PHPDOCK_VERSION" >/dev/null

# Write the version out to disk.
echo "$PHPDOCK_VERSION" > "$PHPDOCK_VERSION_FILE"
