#!/bin/bash

set -e

[ -n "$PHPDOCK_DEBUG" ] && set -x

if [ "$1" = "--debug" ]; then
  export PHPDOCK_DEBUG=true
  shift
fi

if [ -n "$PHPDOCK_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

# Get the basename and main path of script
PROG=`basename $0`
MAIN_PATH=`realpath $0 | xargs dirname | xargs dirname`

shopt -s nullglob

export PATH="$MAIN_PATH/libexec:${PATH}"

shopt -u nullglob


COMMANDS=(`find $MAIN_PATH/libexec/phpdock-* -maxdepth 1 -type f -executable`)

# Show help if non arguments passed to script
[ "$#" -eq 0 ] && ( phpdock-help; exit 1)

COMMAND="$MAIN_PATH/libexec/phpdock-$1"
COMMAND_NAME=$1
shift

if [ -x $COMMAND ]
then
  $COMMAND $@
else
  echo "$PROG: no such command '$COMMAND_NAME'"
fi
