#!/bin/bash
# Summary: Set or show the global php version
# Usage: phpdock global [-a|--apache]
#        phpdock global <version> [-a|--apache]
#        phpdock global --unset [-a|--apache]
#
# Set or show php global version setted
# By default, show php cli version
#
# You can override the global version at any time by setting a
# directory-specific version with 'phpdock local' or by setting
# the 'PHP_CLI_DOCKER_IMAGE' and 'PHP_SERVER_DOCKER_IMAGE'
# environments variables.
#
# <version> should be a string matching a php version known to phpdock
# see 'phpdock versions'
#
# More information at https://github.com/lucasdc6/phpdock#readme

set -e
[ -n "$PHPDOCK_DEBUG" ] && set -x

# Set config variables
COMMAND=`basename $0 | cut -d- -f2`

# Provide phpdock completions
if [ "$1" = "--complete" ]; then
  if echo $@ | grep "\-\-apache" > /dev/null; then
    cat $MAIN_PATH/etc/apache_versions
  else
    cat $MAIN_PATH/etc/cli_versions
  fi
  echo --unset
  echo --apache
  echo --help
  exit 0
fi

# Function to update configuration's files
# Arguments
#   1: file to change
#   2: version to add in file
#   3: type (php-cli|php-apache) in env var format
#       PHP_CLI_DOCKER_IMAGE from php-cli
#       PHP_SERVER_DOCKER_IMAGE from php-apache
function change_file {
  if [ ! -e "$1" ]
  then
    echo "export $3=$2" > $1
  elif grep "^export $3=[[:print:]]*$" $1 > /dev/null
  then
    sed -i -- "s~export $3=.*~export $3=$2~g" $1
  else
    echo "export $3=$2" >> $1
  fi
}

# Function to change global version of php
# Arguments
#   1: version to set as global
function change_php_global {
  if [ "$1" ]
  then
    change_file "$MAIN_PATH/etc/php_global" $1 "PHP_CLI_DOCKER_IMAGE"
    echo "Global php version setted to $1 in file $MAIN_PATH/etc/php_global"
    echo -e "\nRemember restart your terminal"
  elif [ -f "$MAIN_PATH/etc/php_global" ] && grep "PHP_CLI_DOCKER_IMAGE" $MAIN_PATH/etc/php_global > /dev/null
  then
    cat $MAIN_PATH/etc/php_global | grep "PHP_CLI_DOCKER_IMAGE" | cut -d= -f2
  else
    echo "$PROG: no php global version configured"
  fi
}

# Function to change global version of php
# Arguments
#   1. version to set as global
function change_apache_global {
  if [ "$1" ]
  then
    change_file "$MAIN_PATH/etc/php_global" $1 "PHP_SERVER_DOCKER_IMAGE"
    echo "Global php version setted to $1 in file $MAIN_PATH/etc/php_global"
    echo -e "\nRemember restart your terminal"
  elif [ -f "$MAIN_PATH/etc/php_global" ] && grep "PHP_SERVER_DOCKER_IMAGE" $MAIN_PATH/etc/php_global > /dev/null
  then
    cat $MAIN_PATH/etc/php_global | grep "PHP_SERVER_DOCKER_IMAGE" | cut -d= -f2
  else
    echo "$PROG: no apache global version configured"
  fi
}

# Config getopt
TEMP=`getopt -o a,u --long apache,unset -n $PROG -- "$@"`
eval set -- "$TEMP"

# default value of apache
MODE=php

# Parse arguments
while true ; do
  case "$1" in
    -a|--apache)
      MODE=apache
      shift;;
    --unset)
      ACTION=unset
      shift;;
    --) shift ; break ;;
    *) echo "Internal error!" ; exit 1 ;;
  esac
done

if [ "$ACTION" = "unset" ]; then
  if [ "$MODE" = "apache" ]; then
    sed -i "/PHP_SERVER_DOCKER_IMAGE/d" $MAIN_PATH/etc/php_global
  else
    sed -i "/PHP_CLI_DOCKER_IMAGE/d" $MAIN_PATH/etc/php_global
  fi
  exit 0
fi

change_${MODE}_global $1
