#!/usr/bin/env bash
# Summary: List all available phpdock commands
# Usage: phpdock commands [--sh|--no-sh]

set -e

[ -n "$PHPDOCK_DEBUG" ] && set -x

# Set config variables
PROG=`basename $0 | cut -d- -f1`
COMMAND=`basename $0 | cut -d- -f2`
MAIN_PATH=`realpath $0 | xargs dirname | xargs dirname`

# Config getopt
TEMP=`getopt -o h --long help -n $PROG -- "$@"`
eval set -- "$TEMP"

# Parse arguments
while true ; do
  case "$1" in
    -h|--help)
      phpdock-help $COMMAND
      exit 0;;
    --) shift ; break ;;
    *) echo "Internal error!" ; exit 1 ;;
  esac
done

COMMANDS=(`find $MAIN_PATH/libexec/phpdock-* -maxdepth 1 -type f -executable | rev | cut -d/ -f 1 | rev | uniq | sort`)

for COMMAND in ${COMMANDS[@]}; do
  echo ${COMMAND:8}
done
