#!/usr/bin/env bash
# Summary: Display prefix for a php docker version
# Usage: phpdock prefix [<version>]
#
# Displays complete image name of a php version.. If no
# version is given, `phpdock prefix' displays the location of the
# currently selected version.

set -e
[ -n "$PHPDOCK_DEBUG" ] && set -x

# Provide rbenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec phpdock-versions --bare
fi

if [ -n "$1" ]; then
  export PHP_CLI_DOCKER_IMAGE="$1"
elif [ -z "$PHP_CLI_DOCKER_IMAGE" ]; then
  PHP_CLI_DOCKER_IMAGE="$(phpdock-version-name)"
fi

PHPDOCK_PREFIX=`docker images --format "{{.Repository}}:{{.Tag}}" | grep $PHP_CLI_DOCKER_IMAGE`
if [ ! -d "$PHPDOCK_PREFIX" ]; then
  echo "phpdock: version \`${PHP_CLI_DOCKER_IMAGE}' not installed" >&2
  exit 1
fi

echo "$RBENV_PREFIX_PATH"
