#!/usr/bin/env bash
# Summary: Configure the shell environment for phpdock
# Usage: eval "$(phpdock init - [<shell>])"

set -e
[ -n "$PHPDOCK_DEBUG" ] && set -x

# Provide phpdock completions
if [ "$1" = "--complete" ]; then
  echo -
  echo bash
  echo fish
  echo ksh
  echo zsh
  exit
fi

print=""
for args in "$@"
do
  if [ "$args" = "-" ]; then
    print=1
    shift
  fi
done

shell="$1"
if [ -z "$shell" ]; then
  shell="$(ps -p "$PPID" -o 'args=' 2>/dev/null || true)"
  shell="${shell%% *}"
  shell="${shell##-}"
  shell="${shell:-$SHELL}"
  shell="${shell##*/}"
fi

root="${0%/*}/.."

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    if [ -f "${HOME}/.bashrc" ] && [ ! -f "${HOME}/.bash_profile" ]; then
      profile='~/.bashrc'
    else
      profile='~/.bash_profile'
    fi
    ;;
  zsh )
    profile='~/.zshrc'
    ;;
  ksh )
    profile='~/.profile'
    ;;
  fish )
    profile='~/.config/fish/config.fish'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load phpdock automatically by appending"
    echo "# the following to ${profile}:"
    echo
    case "$shell" in
    fish )
      echo 'status --is-interactive; and source (phpdock init -|psub)'
      ;;
    * )
      echo 'eval "$(phpdock init -)"'
      ;;
    esac
    echo
  } >&2

  exit 1
fi

mkdir -p "${PHPDOCK_ROOT}/"{shims,versions}

case "$shell" in
fish )
  echo "set -gx PATH '${PHPDOCK_ROOT}/shims' \$PATH"
  echo "set -gx PHPDOCK_SHELL $shell"
;;
* )
  echo 'export PATH="'${PHPDOCK_ROOT}'/shims:${PATH}"'
  echo "export PHPDOCK_SHELL=$shell"
;;
esac

completion="${root}/completions/phpdock.${shell}"
if [ -r "$completion" ]; then
  echo "source '$completion'"
fi

commands=(`phpdock-commands --sh`)
case "$shell" in
fish )
  cat <<EOS
function phpdock
  set command \$argv[1]
  set -e argv[1]

  switch "\$command"
  case ${commands[*]}
    source (phpdock "sh-\$command" \$argv|psub)
  case '*'
    command phpdock "\$command" \$argv
  end
end
EOS
  ;;
ksh )
  cat <<EOS
function phpdock {
  typeset command
EOS
  ;;
* )
  cat <<EOS
phpdock() {
  local command
EOS
  ;;
esac

if [ "$shell" != "fish" ]; then
IFS="|"
cat <<EOS
  command="\${1:-}"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${commands[*]})
    eval "\$(phpdock "sh-\$command" "\$@")";;
  *)
    command phpdock "\$command" "\$@";;
  esac
}
EOS
fi
