#!/bin/bash
# Summary: Shows the path to the file who set the php version

set -e
[ -n "$PHPDOCK_DEBUG" ] && set -x

# Set config variables
PROG=`basename $0 | cut -d- -f1`
COMMAND=`basename $0 | cut -d- -f2`
MAIN_PATH=`realpath $0 | xargs dirname | xargs dirname`

function upsearch {
  slashes=${PWD//[^\/]/}
  directory="$PWD"
  for (( n=${#slashes}; n>0; --n ))
  do
    test -e "$directory/$1" && echo "$directory/$1" && return
    directory="$directory/.."
  done
}

# Config getopt
TEMP=`getopt -o h --long apache,name,help -n $PROG -- "$@"`
eval set -- "$TEMP"

# Parse arguments
while true ; do
  case "$1" in
    --apache)
      APACHE="--apache"
      shift;;
    -h|--help)
      phpdock-help $COMMAND
      shift
      exit 0;;
    --) shift ; break ;;
    *) echo "Internal error!" ; exit 1 ;;
  esac
done

if phpdock local > /dev/null; then
  ENVRC=`upsearch ".envrc"`
  echo `realpath $ENVRC`
else
  echo $MAIN_PATH/etc/php_global
fi
